/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package catSchool.view;

import catSchool.controller.AlunoController;
import catSchool.controller.ProfessorController;
import catSchool.dao.ExceptionDAO;
import catSchool.model.Aluno;
import catSchool.model.Professor;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junior
 */
public class TelaConsultaProfessor extends javax.swing.JFrame {

    
    private TelaCadastroProfessor telaCadastroProfessor;
    
    private TelaMenu telaMenu;
    
    public TelaConsultaProfessor() {
        initComponents();
    }

    public TelaConsultaProfessor(TelaCadastroProfessor telaCadastroProfessor) {
        this.telaCadastroProfessor = telaCadastroProfessor;
        initComponents();
    }
    
    public TelaConsultaProfessor(TelaMenu telaMenu) {
        this.telaMenu = telaMenu;
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsultaProfessor = new javax.swing.JTable();
        jTextFieldNomeProfessor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableConsultaProfessor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cpf", "Formação", "Identidade Profissional"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableConsultaProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultaProfessorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableConsultaProfessor);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarProfessores(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Informe o nome do professor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNomeProfessor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextFieldNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarProfessores(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarProfessores
        String nome = jTextFieldNomeProfessor.getText();
        
         DefaultTableModel tableModel = (DefaultTableModel) jTableConsultaProfessor.getModel();
        tableModel.setRowCount(0);
        
        try {
            
            
            ArrayList<Professor> professores =  ProfessorController.listarProfessores(nome);
                    
            professores.forEach((Professor professor) -> {
            tableModel.addRow(new Object[]{           
                professor.getNome(),
                professor.getCpf(),
                professor.getFormacao(),
                professor.getIdentidadeProfissional()});    
        });
            
                    

            jTableConsultaProfessor.setModel(tableModel);
        } catch (ExceptionDAO ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_consultarProfessores

    private void jTableConsultaProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultaProfessorMouseClicked
        if(evt.getClickCount() == 2){
            String nome = (String) jTableConsultaProfessor.getModel().getValueAt(jTableConsultaProfessor.getSelectedRow(),0);
            String cpf = (String) jTableConsultaProfessor.getModel().getValueAt(jTableConsultaProfessor.getSelectedRow(),1);
            String formacao = (String) jTableConsultaProfessor.getModel().getValueAt(jTableConsultaProfessor.getSelectedRow(),2);
            String identidadeProfissional = (String) jTableConsultaProfessor.getModel().getValueAt(jTableConsultaProfessor.getSelectedRow(),3);
            this.telaCadastroProfessor.buscarProfessor(nome,cpf,formacao,identidadeProfissional);
            this.telaCadastroProfessor.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jTableConsultaProfessorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultaProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsultaProfessor;
    private javax.swing.JTextField jTextFieldNomeProfessor;
    // End of variables declaration//GEN-END:variables
}
