/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package catSchool.view;

import catSchool.controller.AlunoController;
import catSchool.controller.ProfessorController;
import catSchool.dao.ExceptionDAO;
import java.awt.event.ActionEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author junior
 */
public class TelaCadastroProfessor extends javax.swing.JFrame {

    
    private TelaMenu telaMenu;
    
    private String nome;
    
    public TelaCadastroProfessor() {
        initComponents();
    }
    
    public TelaCadastroProfessor(TelaMenu telaMenu) {
        this.telaMenu = telaMenu;
        initComponents();
    }
    
    public void buscarProfessor(String nome, String cpf, String formacao,String identidadeProfissional){
        this.nome = nome;
        this.jTextFieldNome.setText(nome);
        this.jTextFieldCpf.setText(cpf);
        this.jTextFieldFormacao.setText(formacao);
        this.jTextFieldIdentidadeProfissional.setText(identidadeProfissional);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is alwaysƒ
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonConsultarProfessor1 = new javax.swing.JButton();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldCpf = new javax.swing.JTextField();
        jTextFieldFormacao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldIdentidadeProfissional = new javax.swing.JTextField();
        jButtonSalvarProfessor = new javax.swing.JButton();
        jButtonConsultarProfessor = new javax.swing.JButton();
        jLabelCadastroAluno = new javax.swing.JLabel();
        jButtonConsultarProfessor2 = new javax.swing.JButton();

        jButtonConsultarProfessor1.setText("Consultar");
        jButtonConsultarProfessor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarProfessor1abrirTelaDeConsultarProfessor(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                fecharTelaCadastroProfessor(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Cpf:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Formação");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("identidade profissional");

        jButtonSalvarProfessor.setText("Salvar");
        jButtonSalvarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarProfessor(evt);
            }
        });

        jButtonConsultarProfessor.setText("Consultar");
        jButtonConsultarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirTelaDeConsultarProfessor(evt);
            }
        });

        jLabelCadastroAluno.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelCadastroAluno.setText("Cadastro de professor");

        jButtonConsultarProfessor2.setText("Apagar");
        jButtonConsultarProfessor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarProfessor(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldCpf)
                        .addComponent(jLabel4)
                        .addComponent(jTextFieldIdentidadeProfissional))
                    .addComponent(jLabel2))
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSalvarProfessor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonConsultarProfessor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonConsultarProfessor2)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelCadastroAluno)
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelCadastroAluno)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIdentidadeProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarProfessor)
                    .addComponent(jButtonConsultarProfessor)
                    .addComponent(jButtonConsultarProfessor2))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarProfessor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarProfessor
        String nome = jTextFieldNome.getText();
        String cpf = jTextFieldCpf.getText();
        String formacao = jTextFieldFormacao.getText();
        String identidadeProfissional = jTextFieldIdentidadeProfissional.getText();
        
        try {
            boolean conseguiuCadastrarProfessor = ProfessorController.cadastrarProfessor(nome,cpf,formacao,identidadeProfissional);
            if(conseguiuCadastrarProfessor){
            JOptionPane.showMessageDialog(null, "Professor cadastrado com sucesso ");
            this.limparTelaCadastroProfessor(evt);
            }else{
             JOptionPane.showMessageDialog(null, "Dados não foram inseridos corretamente");

            }
                
        } catch (ExceptionDAO ex) {
            JOptionPane.showMessageDialog(null, "Erro: "+ ex);
        }
                

    }//GEN-LAST:event_salvarProfessor

    private void abrirTelaDeConsultarProfessor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirTelaDeConsultarProfessor
        TelaConsultaProfessor telaConsultaProfessor = new TelaConsultaProfessor(this);
        this.setVisible(false);
        telaConsultaProfessor.setVisible(true);
    }//GEN-LAST:event_abrirTelaDeConsultarProfessor

    private void fecharTelaCadastroProfessor(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fecharTelaCadastroProfessor
        this.dispose();
        telaMenu.setVisible(true);
    }//GEN-LAST:event_fecharTelaCadastroProfessor

    private void jButtonConsultarProfessor1abrirTelaDeConsultarProfessor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarProfessor1abrirTelaDeConsultarProfessor
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConsultarProfessor1abrirTelaDeConsultarProfessor

    private void apagarProfessor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarProfessor
        boolean conseguiuApagarProfessor;
        ProfessorController professorController = new ProfessorController();
        try{
            conseguiuApagarProfessor = professorController.apagarProfessor(this.nome);
            if(conseguiuApagarProfessor){
               JOptionPane.showMessageDialog(null, "O professor foi apagado com sucesso");
               this.limparTelaCadastroProfessor(evt);
            }else{
                JOptionPane.showMessageDialog(null, "O professor não foi apagado. Por favor selecione um aluno");
            }
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, "Erro: "+e);

        }
    }//GEN-LAST:event_apagarProfessor

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultarProfessor;
    private javax.swing.JButton jButtonConsultarProfessor1;
    private javax.swing.JButton jButtonConsultarProfessor2;
    private javax.swing.JButton jButtonSalvarProfessor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCadastroAluno;
    private javax.swing.JTextField jTextFieldCpf;
    private javax.swing.JTextField jTextFieldFormacao;
    private javax.swing.JTextField jTextFieldIdentidadeProfissional;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables

    private void limparTelaCadastroProfessor(ActionEvent evt) {
        jTextFieldNome.setText("");
        jTextFieldCpf.setText("");
        jTextFieldFormacao.setText("");
        jTextFieldIdentidadeProfissional.setText("");
    }

    
}
